apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: feature-flag-service
  description: Feature flag evaluation service with percentage rollouts, targeting rules, and audit logging
  annotations:
    github.com/project-slug: DSurya11/feature-flag-service
  links:
    - url: https://github.com/DSurya11/idp-gitops
      title: Env Config Repo (GitOps)
    - url: https://github.com/DSurya11/feature-flag-service/pkgs/container/feature-flag-service
      title: Container Images (GHCR)
    - url: http://localhost:8000/docs
      title: API Docs (Swagger)
  tags:
    - fastapi
    - python
    - postgres
    - redis
spec:
  type: service
  lifecycle: experimental
  owner: DSurya11
  dependsOn:
    - resource:default/feature-flag-postgres
    - resource:default/feature-flag-redis
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: feature-flag-postgres
  description: Neon-hosted Postgres database for the Feature Flag Service, provisioned via Terraform
spec:
  type: database
  owner: DSurya11
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: feature-flag-redis
  description: In-cluster Redis cache for flag evaluation
spec:
  type: cache
  owner: DSurya11
