"""
routers/metrics.py — GET /metrics endpoint (Prometheus exposition format).

Auth: deliberately none.
--------------------------
This is the only endpoint in the service that requires no JWT.  This is an
explicit, deliberate design decision — not an oversight.

Prometheus's scraper is a separate infrastructure component.  It operates on
a fixed scrape interval, authenticates via network policy (it can only reach
the metrics port from within the cluster), and cannot be expected to obtain or
renew a JWT.  Forcing auth here would require a second, separate authentication
mechanism solely for the scraper (e.g. a static bearer token or client certificate)
which is out of scope for this portfolio project and adds no security value when
the metrics port is already firewalled to cluster-internal traffic.

This is the same pattern used by the vast majority of production Prometheus
exporters and Kubernetes workloads: the /metrics path is protected by network
policy, not application-layer auth.  The decision is documented in README.md
alongside the analogous /evaluate auth limitation note from Step 5.

Response format: Prometheus text exposition format 0.0.4
---------------------------------------------------------
The response body is generated by prometheus-client's generate_latest() — we do
NOT hand-construct this string.  The Content-Type is set by make_asgi_app() or
by using the CONTENT_TYPE_LATEST constant; we use the constant directly here so
that FastAPI's Response can carry it without fighting the framework's default
JSON serialization.
"""

import logging

from fastapi import APIRouter
from fastapi.responses import Response
from prometheus_client import CONTENT_TYPE_LATEST, generate_latest

logger = logging.getLogger(__name__)

router = APIRouter(tags=["metrics"])


@router.get(
    "/metrics",
    summary="Prometheus metrics",
    description=(
        "Expose internal counters and histograms in Prometheus text exposition "
        "format.  No authentication required — this endpoint is intended for "
        "Prometheus scrapers operating within the same network, not for human "
        "or API consumers.  See README.md for the deliberate no-auth rationale."
    ),
    # Exclude from OpenAPI auth schemes — this endpoint has no security requirement.
    include_in_schema=True,
)
def get_metrics() -> Response:
    """
    GET /metrics

    Returns the current state of all registered Prometheus metrics in the
    standard Prometheus text exposition format.  The response body is generated
    by prometheus-client's generate_latest() — never hand-constructed.

    Content-Type is set to CONTENT_TYPE_LATEST, which is the exact value
    Prometheus expects (``text/plain; version=0.0.4; charset=utf-8``).
    """
    logger.debug("GET /metrics — generating Prometheus exposition output.")
    return Response(
        content=generate_latest(),
        media_type=CONTENT_TYPE_LATEST,
    )
