"""initial_schema

Revision ID: 3dbddf30514d
Revises: 
Create Date: 2026-09-12 15:54:09.772498+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dbddf30514d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('flag_type', sa.Enum('boolean', 'percentage', 'targeted', name='flagtype'), nullable=False),
    sa.Column('default_value', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rollout_percentage', sa.Integer(), nullable=True),
    sa.Column('environment', sa.Enum('dev', 'staging', 'prod', name='environment'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rollout_percentage IS NULL OR (rollout_percentage >= 0 AND rollout_percentage <= 100)', name='ck_flags_rollout_percentage_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'environment', name='uq_flags_name_environment')
    )
    op.create_index(op.f('ix_flags_name'), 'flags', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'viewer', name='userrole'), server_default='viewer', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('created', 'updated', 'deleted', name='auditaction'), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targeting_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('attribute', sa.String(), nullable=False),
    sa.Column('operator', sa.Enum('equals', 'in', 'not_equals', name='operator'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('targeting_rules')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_flags_name'), table_name='flags')
    op.drop_table('flags')
    # ### end Alembic commands ###
    # Drop Postgres native enum types — autogenerate does not emit these.
    sa.Enum(name='operator').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='auditaction').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='environment').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='flagtype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)

